### ISSUE TITLE
Intermittent test failures with Kinto in CI

### ISSUE THREAD

**Issue by ncloudioj** [mozilla-services/merino#250]
We're getting intermittent test failures in CI, the Kinto service running inside of docker-composer failed with the attached error, which prevented certain integration tests from making progress as all the requests to Kinto failed.

```
kinto_1              | unable to load app 0 (mountpoint='') (callable not found or import error)
kinto_1              | /usr/local/lib/python3.9/site-packages/kinto/core/initialization.py:567: UserWarning: HTTPS is not enabled
kinto_1              |   warnings.warn("HTTPS is not enabled")
kinto_1              | Traceback (most recent call last):
kinto_1              |   File "app.wsgi", line 31, in <module>
kinto_1              |     application = main(config.items('DEFAULT'), **dict(config.items('app:main')))
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/kinto/__init__.py", line 51, in main
kinto_1              |     kinto.core.initialize(config, version=__version__, default_settings=DEFAULT_SETTINGS)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/kinto/core/initialization.py", line 585, in initialize
kinto_1              |     config.include("kinto.core", route_prefix=api_version)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 666, in include
kinto_1              |     c(configurator)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/kinto/core/__init__.py", line 214, in includeme
kinto_1              |     config.include(app)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 632, in include
kinto_1              |     c = self.maybe_dotted(callable)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
kinto_1              |     return self.name_resolver.maybe_resolve(dotted)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 327, in maybe_resolve
kinto_1              |     return self._resolve(dotted, package)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 334, in _resolve
kinto_1              |     return self._zope_dottedname_style(dotted, package)
kinto_1              |   File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 383, in _zope_dottedname_style
kinto_1              |     found = __import__(used)
kinto_1              | ModuleNotFoundError: No module named 'kinto_changes
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1399)

**Comment by mythmon** [comment]
Looking around, it seems that https://github.com/mozilla-services/kinto-dist has changed how they handle the `kinto_changes` feature (specifically, merging it with `kinto_signer`). https://github.com/mozilla-services/kinto-dist/blob/main/CHANGELOG.rst

This is at least a clear cause of what we're seeing, and it explains why it just started. We should look into both pinning our version of kinto-dist, and also figuring out how we can adapt to the changes in v26.
